package com.civicdesk.analytics.controller;

import com.civicdesk.analytics.dto.*;
import com.civicdesk.analytics.enums.ReportType;
import com.civicdesk.analytics.security.JwtUserContext;
import com.civicdesk.analytics.service.AnalyticsService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/civicDesk/analytics")
@RequiredArgsConstructor
@Tag(name = "Analytics & Reports", description = "Civic reports and dashboard metrics for supervisors and compliance officers")
@SecurityRequirement(name = "BearerAuth")
public class AnalyticsController {

    private final AnalyticsService analyticsService;

    // ─── DASHBOARD ────────────────────────────────────────────────────────────

    @GetMapping("/dashboard")
    @PreAuthorize("hasAnyRole('CO','DS','ADM')")
    @Operation(summary = "Get dashboard metrics",
            description = "ROLE_COMPLIANCE, ROLE_DEPT_SUPERVISOR, ROLE_ADMIN. Returns aggregate counts across all CivicDesk modules. In a full deployment these are populated via an event-driven pipeline; this endpoint returns the current analytics DB snapshot.")
    public ResponseEntity<ApiResponse<DashboardMetrics>> getDashboard() {
        return ResponseEntity.ok(ApiResponse.<DashboardMetrics>builder()
                .success(true).data(analyticsService.getDashboard()).build());
    }

    // ─── REPORTS ─────────────────────────────────────────────────────────────

    @PostMapping("/reports/generate")
    @PreAuthorize("hasAnyRole('CO','ADM')")
    @Operation(summary = "Generate a civic report",
            description = "ROLE_COMPLIANCE, ROLE_ADMIN. Generates a report snapshot of the specified type. Optional filters: departmentId, fromDate (yyyy-MM-dd), toDate (yyyy-MM-dd). Report is saved to DB for later retrieval.")
    public ResponseEntity<ApiResponse<CivicReportResponse>> generateReport(
            @Valid @RequestBody GenerateReportRequest request) {
        Long userId = JwtUserContext.getCurrentUserId();
        CivicReportResponse response = analyticsService.generateReport(request, userId);
        return ResponseEntity.ok(ApiResponse.<CivicReportResponse>builder()
                .success(true).message("Report generated: " + response.getReportName()).data(response).build());
    }

    @GetMapping("/reports")
    @PreAuthorize("hasAnyRole('CO','DS','ADM')")
    @Operation(summary = "List all reports",
            description = "ROLE_COMPLIANCE, ROLE_DEPT_SUPERVISOR, ROLE_ADMIN. Returns all stored reports, newest first. Optional filter by reportType.")
    public ResponseEntity<ApiResponse<List<CivicReportResponse>>> getAll(
            @RequestParam(required = false) ReportType reportType) {
        List<CivicReportResponse> data = reportType != null
                ? analyticsService.getByType(reportType)
                : analyticsService.getAll();
        return ResponseEntity.ok(ApiResponse.<List<CivicReportResponse>>builder()
                .success(true).data(data).build());
    }

    @GetMapping("/reports/my")
    @PreAuthorize("hasAnyRole('CO','DS','ADM')")
    @Operation(summary = "List reports generated by me",
            description = "ROLE_COMPLIANCE, ROLE_DEPT_SUPERVISOR, ROLE_ADMIN. Returns reports generated by the logged-in user.")
    public ResponseEntity<ApiResponse<List<CivicReportResponse>>> getMyReports() {
        Long userId = JwtUserContext.getCurrentUserId();
        return ResponseEntity.ok(ApiResponse.<List<CivicReportResponse>>builder()
                .success(true).data(analyticsService.getMyReports(userId)).build());
    }

    @GetMapping("/reports/{reportId}")
    @PreAuthorize("hasAnyRole('CO','DS','ADM')")
    @Operation(summary = "Get report by ID",
            description = "ROLE_COMPLIANCE, ROLE_DEPT_SUPERVISOR, ROLE_ADMIN. Retrieve full report data including the stored JSON snapshot.")
    public ResponseEntity<ApiResponse<CivicReportResponse>> getById(@PathVariable Long reportId) {
        return ResponseEntity.ok(ApiResponse.<CivicReportResponse>builder()
                .success(true).data(analyticsService.getById(reportId)).build());
    }

    @DeleteMapping("/reports/{reportId}")
    @PreAuthorize("hasRole('ADM')")
    @Operation(summary = "Delete a report",
            description = "ROLE_ADMIN only. Permanently deletes a stored report.")
    public ResponseEntity<ApiResponse<Void>> deleteReport(@PathVariable Long reportId) {
        analyticsService.deleteReport(reportId);
        return ResponseEntity.ok(ApiResponse.<Void>builder()
                .success(true).message("Report deleted.").build());
    }
}
