# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/service-request-service-1.0.0.jar app.jar
RUN mkdir -p logs
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
