server.port=8084
spring.application.name=permit-service

spring.datasource.url=jdbc:mysql://localhost:3306/civicdesk_permit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=4a6250655368566d5970337336763979244226452948404d6351665468819ad2

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.level.com.civicdesk=DEBUG
logging.level.org.springframework.security=INFO
logging.config=classpath:logback-spring.xml

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Permit Service
info.app.version=1.0.0
info.app.description=CivicDesk Permit Microservice


app.notification-service.url=http://localhost:8087
app.gateway.url=http://localhost:9090

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

