package com.civicdesk.citizen.service;


import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.ExceptionHandler;

import com.civicdesk.citizen.dto.response.DocumentDetailResponse;
import com.civicdesk.citizen.dto.response.DocumentSummaryResponse;
import com.civicdesk.citizen.entity.CitizenDocument;
import com.civicdesk.citizen.enums.DocumentStatus;
import com.civicdesk.citizen.enums.DocumentType;
import com.civicdesk.citizen.exception.ForbiddenActionException;
import com.civicdesk.citizen.exception.InvalidRequestException;
import com.civicdesk.citizen.exception.ResourceNotFoundException;
import com.civicdesk.citizen.repository.CitizenDocumentRepository;
import com.civicdesk.citizen.repository.CitizenProfileRepository;
import com.civicdesk.citizen.support.FileStorageService;
import com.civicdesk.citizen.support.IdGenerator;
import com.civicdesk.citizen.util.SecurityContextUtil;

import java.io.ByteArrayInputStream;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Business logic for the citizen <b>document wallet</b>: the store of government-issued documents
 * (birth certificate, caste certificate, …) generated by the service-request module.
 *
 * <p>{@code citizenId} on these operations is the owning citizen's {@code userId}. The
 * service-request module pushes a generated document by calling {@link #addDocument} in-process
 * (no HTTP). Citizens list / view / download their own documents (CIT-only).
 */
@Service
@Transactional(readOnly = true)
public class DocumentService {

    private final CitizenDocumentRepository documentRepository;
    private final CitizenProfileRepository citizenRepository;
    private final FileStorageService fileStorage;

    public DocumentService(CitizenDocumentRepository documentRepository,
                           CitizenProfileRepository citizenRepository,
                           FileStorageService fileStorage) {
        this.documentRepository = documentRepository;
        this.citizenRepository = citizenRepository;
        this.fileStorage = fileStorage;
    }

    /**
     * Pushes a generated document into a citizen's wallet. Intended for in-process use by the
     * service-request module (autowire {@code DocumentService}). The bytes are stored on disk and a
     * wallet record is created with status {@link DocumentStatus#Valid}.
     *
     * @param citizenUserId   the owning citizen's userId (must exist, else 404)
     * @param documentType    a {@link DocumentType} code
     * @param originalFileName the generated file's name (used for the extension)
     * @param content         the file bytes
     * @param issuedDate      when the document was issued (nullable)
     * @param expiryDate      when it expires (nullable)
     * @return the generated {@code documentId}
     */
    @Transactional
    public String addDocument(String citizenUserId, String documentType, String originalFileName,
                              byte[] content, LocalDate issuedDate, LocalDate expiryDate) {
        requireCitizenExists(citizenUserId);
        DocumentType type = parseEnum(DocumentType.class, documentType, "documentType");
        if (content == null || content.length == 0) {
            throw new InvalidRequestException("Document content is empty");
        }



        String ext = extensionOf(originalFileName);
        String storedName = ext.isEmpty() ? IdGenerator.newId() : IdGenerator.newId() + "." + ext;
        fileStorage.store(new ByteArrayInputStream(content), storedName);

        // Verify the file actually landed at the expected location before recording it, so the
        // wallet never holds a record pointing at a missing file.
        if (!fileStorage.exists(storedName)) {
            fileStorage.deleteQuietly(storedName);
            throw new InvalidRequestException(
                    "Document file was not stored at the expected location: " + storedName);
        }

        CitizenDocument document = new CitizenDocument();
        document.setCitizenId(citizenUserId);
        document.setDocumentType(type);
        document.setFileName(originalFileName);
        document.setFilePath(storedName);
        document.setFileType(ext);
        document.setFileSizeKb((int) Math.ceil(content.length / 1024.0));
        document.setIssuedDate(issuedDate);
        document.setExpiryDate(expiryDate);
        document.setStatus(DocumentStatus.Valid);
        documentRepository.save(document);
        return document.getDocumentId();
    }

    /** Lists every document for the current citizen's own wallet (404 if the citizen does not exist). */
    public List<DocumentSummaryResponse> getAllDocuments(String citizenId) {
        requireSelf(citizenId);
        requireCitizenExists(citizenId);
        return documentRepository.findByCitizenId(citizenId).stream()
                .map(DocumentService::toSummary)
                .toList();
    }

    /** Returns one of the current citizen's own documents (404 if not found for that citizen). */
    public DocumentDetailResponse getDocumentById(String citizenId, String documentId) {
        requireSelf(citizenId);
        CitizenDocument document = documentRepository
                .findByDocumentIdAndCitizenId(documentId, citizenId)
                .orElseThrow(() -> new ResourceNotFoundException("Document not found: " + documentId));
        return toDetail(document);
    }

    /** Resolves the stored file name for one of the current citizen's own documents. */
    public String resolveDownloadFileName(String citizenId, String documentId) {
        requireSelf(citizenId);
        CitizenDocument document = documentRepository
                .findByDocumentIdAndCitizenId(documentId, citizenId)
                .orElseThrow(() -> new ResourceNotFoundException("Document not found: " + documentId));
        return document.getFilePath();
    }


    // ---------------------------------------------------------------------------------------------
    // Helpers
    // ---------------------------------------------------------------------------------------------

    /** A {@code CIT} caller may act only on their own documents (path id must equal the JWT id). */
    private void requireSelf(String citizenId) {
        if (!citizenId.equals(currentUserId())) {
            throw new ForbiddenActionException("You can only access your own documents");
        }
    }


    /** A still-{@code Valid} document past its {@code expiryDate} reads as {@code Expired}. */
    private static DocumentStatus effectiveStatus(CitizenDocument d) {
        if (d.getStatus() == DocumentStatus.Valid
                && d.getExpiryDate() != null
                && d.getExpiryDate().isBefore(LocalDate.now())) {
            return DocumentStatus.Expired;
        }
        return d.getStatus();
    }

    private void requireCitizenExists(String citizenId) {
        if (!citizenRepository.existsById(citizenId)) {
            throw new ResourceNotFoundException("Citizen not found: " + citizenId);
        }
    }

    /** Lowercased extension without the dot, or "" if none. */
    private static String extensionOf(String fileName) {
        if (fileName == null) {
            return "";
        }
        int dot = fileName.lastIndexOf('.');
        if (dot < 0 || dot == fileName.length() - 1) {
            return "";
        }
        return fileName.substring(dot + 1).toLowerCase();
    }

    private static DocumentSummaryResponse toSummary(CitizenDocument d) {
        return new DocumentSummaryResponse(
                d.getDocumentId(),
                d.getDocumentType().name(),
                d.getFileName(),
                d.getFileType(),
                d.getFileSizeKb(),
                effectiveStatus(d).getCode(),
                d.getIssuedDate(),
                d.getExpiryDate(),
                d.getVerifiedAt(),
                d.getUploadedAt());
    }

    private static DocumentDetailResponse toDetail(CitizenDocument d) {
        return new DocumentDetailResponse(
                d.getDocumentId(),
                d.getCitizenId(),
                d.getDocumentType().name(),
                d.getFileName(),
                d.getFilePath(),
                d.getFileType(),
                d.getFileSizeKb(),
                d.getIssuedDate(),
                d.getExpiryDate(),
                effectiveStatus(d).getCode(),
                d.getVerifiedBy(),
                d.getVerifiedAt(),
                d.getUploadedAt());
    }

    /** Parses a String into an enum constant, raising a precise 400 listing the allowed values. */
    private static <E extends Enum<E>> E parseEnum(Class<E> type, String value, String field) {
        try {
            return Enum.valueOf(type, value);
        } catch (IllegalArgumentException | NullPointerException e) {
            String allowed = Arrays.stream(type.getEnumConstants())
                    .map(Enum::name)
                    .collect(Collectors.joining(", "));
            throw new InvalidRequestException(
                    "Invalid " + field + ": '" + value + "'. Allowed values: " + allowed);
        }
    }

    private static String currentUserId() {
        String userId = SecurityContextUtil.getCurrentUserId();
        if (userId == null) {
            throw new ForbiddenActionException("No authenticated user in the security context");
        }
        return userId;
    }
}
