spring.application.name=grievance-service

spring.profiles.active=dev

app.jwt.secret=civicdesk_hs256_secret_key_minimum_32_characters_required

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

logging.config=classpath:logback-spring.xml