server.port=8085
server.servlet.context-path=/civicDesk

spring.datasource.url=jdbc:mysql://localhost:3306/civicdesk_grievance?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

auth.service.url=http://localhost:8081/civicDesk